Repository stylelint/vscode-stylelint, pull requests merged in 2021-11, with the labels that each got.

#294 refactor: Check `this.#logger` separately
  src/utils/packages/stylelint-resolver.js
Labels: Refactor, For Uncommitted Issue

#279 test: add cspell, fix spelling where needed
  .github/workflows/linting.yml
  CHANGELOG.md
  README.md
  cspell.config.js
  package-lock.json
  package.json
  src/index.js
  src/utils/lsp/__tests__/__snapshots__/create-disable-completion-item.js.snap
  src/utils/lsp/__tests__/create-disable-completion-item.js
  src/utils/packages/__tests__/global-path-resolver.js
  src/utils/packages/stylelint-resolver.js
  src/utils/stylelint/__tests__/get-disable-diagnostic-rule.js
  src/utils/stylelint/build-stylelint-options.js
  test/e2e/custom-syntax/__snapshots__/index.js.snap
  test/e2e/custom-syntax/index.js
  test/e2e/validate/__snapshots__/index.js.snap
  test/e2e/validate/index.js
  test/integration/stylelint-vscode/__snapshots__/test.js.snap
  test/integration/stylelint-vscode/test.js
  types/index.d.ts
Labels: For Milestone Issue

#287 test: consolidate tests using extension defaults
  src/index.js
  test/e2e/basic/.stylelintignore
  test/e2e/basic/index.js
  test/e2e/defaults/__snapshots__/format.js.snap
  test/e2e/defaults/__snapshots__/lint.js.snap
  test/e2e/defaults/__snapshots__/resolve-local.js.snap
  test/e2e/defaults/format.js
  test/e2e/defaults/ignore.js
  test/e2e/defaults/jest-runner-vscode.config.js
  test/e2e/defaults/lint.js
  test/e2e/defaults/resolve-local.js
  test/e2e/defaults/workspace/.stylelintignore
  test/e2e/defaults/workspace/.vscode/settings.json
  test/e2e/defaults/workspace/format.css
  test/e2e/defaults/workspace/ignored.css
  test/e2e/defaults/workspace/lint.css
  test/e2e/defaults/workspace/local-stylelint/.gitignore
  test/e2e/defaults/workspace/local-stylelint/node_modules/stylelint/index.js
  test/e2e/defaults/workspace/local-stylelint/node_modules/stylelint/package.json
  test/e2e/defaults/workspace/local-stylelint/test.css
  test/e2e/defaults/workspace/rule-doc.css
  test/e2e/defaults/workspace/stylelint.config.js
  test/e2e/defaults/workspace/test-plugin.js
  test/e2e/formatter/__snapshots__/index.js.snap
  test/e2e/jest.config.js
  test/e2e/lint/.vscode/settings.json
  test/e2e/lint/index.js
  test/e2e/lint/stylelint.config.js
  test/e2e/lint/test.md
  test/e2e/rule-doc/__snapshots__/index.js.snap
  test/e2e/rule-doc/index.js
  test/e2e/rule-doc/stylelint.config.js
  types/index.d.ts
Labels: For Backlog Issue

#308 Bump `eslint-config-stylelint` from 14.0.0 to 15.0.0
  package-lock.json
  package.json
  src/utils/__tests__/iterables.js
  src/utils/iterables.js
  src/utils/lsp/display-error.js
Labels: Dependencies, For Uncommitted Issue

#273 feat: PnP package resolution support
  .eslintignore
  .prettierignore
  CHANGELOG.md
  src/utils/packages/__tests__/__snapshots__/find-package-root.js.snap
  src/utils/packages/__tests__/find-package-root.js
  src/utils/packages/__tests__/stylelint-resolver.js
  src/utils/packages/find-package-root.js
  src/utils/packages/stylelint-resolver.js
  test/e2e/jest.config.js
  test/e2e/yarn-2-pnp/.pnp.js
  test/e2e/yarn-2-pnp/.yarn/install-state.gz
  test/e2e/yarn-2-pnp/.yarn/releases/yarn-2.4.3.cjs
  test/e2e/yarn-2-pnp/.yarnrc.yml
  test/e2e/yarn-2-pnp/__snapshots__/index.js.snap
  test/e2e/yarn-2-pnp/index.js
  test/e2e/yarn-2-pnp/package.json
  test/e2e/yarn-2-pnp/stylelint/index.js
  test/e2e/yarn-2-pnp/stylelint/package.json
  test/e2e/yarn-2-pnp/test.css
  test/e2e/yarn-2-pnp/yarn.lock
  test/e2e/yarn-pnp/.pnp.cjs
  test/e2e/yarn-pnp/.yarn/install-state.gz
  test/e2e/yarn-pnp/.yarn/releases/yarn-3.0.2.cjs
  test/e2e/yarn-pnp/.yarnrc.yml
  test/e2e/yarn-pnp/__snapshots__/index.js.snap
  test/e2e/yarn-pnp/index.js
  test/e2e/yarn-pnp/package.json
  test/e2e/yarn-pnp/stylelint/index.js
  test/e2e/yarn-pnp/stylelint/package.json
  test/e2e/yarn-pnp/test.css
  test/e2e/yarn-pnp/yarn.lock
  test/integration/jest.config.js
  test/unit/jest.config.js
Labels: For Milestone Issue

#302 feat: log all resolution errors
  src/utils/functions/__tests__/get-first-return-value.js
  src/utils/packages/stylelint-resolver.js
Labels: For Uncommitted Issue

#310 fix: properly serialize errors sent to logger
  package-lock.json
  package.json
  src/start-server.js
  src/utils/__tests__/errors.js
  src/utils/errors.js
  src/utils/logging/__tests__/error-formatter.js
  src/utils/logging/error-formatter.js
  src/utils/logging/index.js
  types/index.d.ts
Labels: For Milestone Issue

#314 fix: handle failed global node_modules resolution
  src/utils/packages/__mocks__/global-path-resolver.js
  src/utils/packages/__tests__/__snapshots__/global-path-resolver.js.snap
  src/utils/packages/__tests__/global-path-resolver.js
  src/utils/packages/__tests__/stylelint-resolver.js
  src/utils/packages/global-path-resolver.js
  src/utils/packages/stylelint-resolver.js
  types/index.d.ts
  types/tests.d.ts
Labels: For Milestone Issue

#305 Rebrand — Option C, update description, keep existing logo
  package.json
Labels: For Milestone Issue

#325 fix: make hovering over problems more reliable
  src/utils/stylelint/__tests__/__snapshots__/process-linter-result.ts.snap
  src/utils/stylelint/__tests__/__snapshots__/stylelint-runner.ts.snap
  src/utils/stylelint/__tests__/__snapshots__/warning-to-diagnostic.ts.snap
  src/utils/stylelint/warning-to-diagnostic.ts
  test/e2e/__tests__/__snapshots__/config-basedir.ts.snap
  test/e2e/__tests__/__snapshots__/config-file.ts.snap
  test/e2e/__tests__/__snapshots__/ignore-disables.ts.snap
  test/e2e/__tests__/__snapshots__/lint.ts.snap
  test/e2e/__tests__/__snapshots__/report-invalid-scope-disables.ts.snap
  test/e2e/__tests__/__snapshots__/report-needless-disables.ts.snap
  test/e2e/__tests__/__snapshots__/stylelint-resolution.ts.snap
  test/e2e/__tests__/__snapshots__/validate.ts.snap
  test/integration/stylelint-vscode/__snapshots__/test.ts.snap
Labels: For Milestone Issue

#326 feat: Allow disposing server, add first LSP test
  src/extension/start-server.ts
  src/server/__tests__/__snapshots__/server.ts.snap
  src/server/__tests__/create-logger.ts
  src/server/__tests__/server.ts
  src/server/create-logger.ts
  src/server/index.ts
  src/server/modules/__tests__/__snapshots__/formatter.ts.snap
  src/server/modules/__tests__/auto-fix.ts
  src/server/modules/__tests__/code-action.ts
  src/server/modules/__tests__/completion.ts
  src/server/modules/__tests__/formatter.ts
  src/server/modules/__tests__/old-stylelint-warning.ts
  src/server/modules/__tests__/validator.ts
  src/server/modules/auto-fix.ts
  src/server/modules/code-action.ts
  src/server/modules/completion.ts
  src/server/modules/formatter.ts
  src/server/modules/old-stylelint-warning.ts
  src/server/modules/validator.ts
  src/server/server.ts
  src/server/types.ts
  src/utils/logging/__tests__/language-server-transport.ts
  src/utils/logging/language-server-transport.ts
  src/utils/lsp/__tests__/command-manager.ts
  src/utils/lsp/__tests__/notification-manager.ts
  src/utils/lsp/command-manager.ts
  src/utils/lsp/notification-manager.ts
  src/utils/types.ts
  test/integration/connection-manager.ts
  test/integration/jest.config.js
  test/integration/server/__tests__/initialization.ts
  test/integration/setup.ts
  test/types.d.ts
  test/unit/server-mocks.ts
Labels: For Backlog Issue

#339 feat: Add restart server command
  package.json
  src/extension/__tests__/extension.ts
  src/extension/extension.ts
  test/e2e/__tests__/restart.ts
  test/e2e/setup.ts
Labels: For Milestone Issue

#341 test: add code actions on save end-to-end test
  test/e2e/__tests__/__snapshots__/code-actions.ts.snap
  test/e2e/__tests__/code-actions.ts
  test/e2e/setup.ts
  test/e2e/workspace/code-actions/.vscode/settings.json
Labels: For Milestone Issue

#340 feat: Warn for old Stylelint regardless of language ID
  src/server/modules/__tests__/old-stylelint-warning.ts
  src/server/modules/old-stylelint-warning.ts
Labels: For Milestone Issue
